#index:
#    path: /
#    controller: App\Controller\DefaultController::index
users:
    type: rest
    resource: App\Controller\UsersController

masters:
    type: rest
    resource: App\Controller\MasterController

creditcards:
    type: rest
    resource: App\Controller\CreditcardController

companies:
    type: rest
    resource: App\Controller\CompanyController


articles:
    type: rest
    resource: App\Controller\ArticlesController

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
